default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_backend_kit_development

test:
  <<: *default
  database: rails_backend_kit_test

production:
  primary: &primary_production
    <<: *default
    database: rails_backend_kit_production
    username: rails_backend_kit
    password: <%= ENV["RAILS_BACKEND_KIT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_backend_kit_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_backend_kit_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_backend_kit_production_cable
    migrations_paths: db/cable_migrate
